name: Publish Docker image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1 
        with:
          registry: docker.io
          username: mattmajestic
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: mattmajestic/${{ github.repository }}:latest

      - name: Check if the image was pushed
        id: check_image
        run: |
          IMAGE_NAME=mattmajestic/${{ github.repository }}:latest
          RESPONSE=$(curl --write-out %{http_code} --silent --output /dev/null https://hub.docker.com/v2/repositories/$IMAGE_NAME)
          if [ $RESPONSE -eq 200 ]; then
            echo "Image $IMAGE_NAME exists on Docker Hub."
          else
            echo "Image $IMAGE_NAME does not exist on Docker Hub."
            exit 1
          fi
        shell: bash